# Generated by Django 4.0.2 on 2022-02-09 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.CharField(default=50, max_length=50),
            preserve_default=False,
        ),
    ]
